<h3>This new page is generated by CRM/CMS/Page/Debug.php</h3>

{* Example: Display a variable directly *}
<p>The current time is {$currentTime}</p>

{* Example: Display a translated string -- which happens to include a variable *}
<p>{ts 1=$currentTime}(In your native language) The current time is %1.{/ts}</p>

{foreach from=$Items item=Item}
   {$Item.Item.group} - {$Item.Item.label} - {$Item.Item.weight}- {$Item.Item.value} <br/>

{/foreach}
